### PR TITLE
Doc renderer cluster

### PR DESCRIPTION
**Pull request by huntc**
As well as some general improvements for Play 2.4, this PR transforms play-doc into a clustered application that propagates the receipt of webhook events across all instances of play-doc.

### CODE REVIEW

**Comment by huntc** [comment]
@jroper Can you please review commit 7f04c89 w.r.t. to the conversation we had on Friday re. Play 2.4 DI application?

**Comment by huntc** [comment]
@jroper Can you please advise on how https://github.com/typesafehub/project-doc/blob/master/app/plugins/ConductrPlugin.scala may be re-factored as a Module that reliabily signals ConductR (`StatusService.signalStartedOrExit()`) after the http port has been successfully bound? Thanks.

**Comment by jroper** [comment]
The http port can, as of a change Rich made last week, be configured in the `application.conf`.  To signal conductr after the http port is bound, you'll have to implement a custom main class that invokes Play's main class.  Once the main method returns, you can be assured that http port is bound.  We don't currently have a callback for when the http port is bound in Play itself - perhaps we could add one.

But, thinking over all this, perhaps it would be better if rather than hooking into Play itself, which would require users to configure their Play apps in a particular way, you just have your own server main class.  One reason why this might make sense is because when the user is developing the app in dev mode, you probably don't want anything you do to get involved at all, it's only in prod mode that you want this custom behaviour to happen.  Here's the interface to starting an app in Play (note, this does not exist in 2.4.0-M3, only in master):

https://github.com/playframework/playframework/blob/master/framework/src/play-server/src/main/scala/play/core/server/ProdServerStart.scala

And the ServerProcess interface:

https://github.com/playframework/playframework/blob/master/framework/src/play-server/src/main/scala/play/core/server/ServerProcess.scala

So you could instantiate a ProdServerStart, and implement your own ServerProcess interface that contained anything custom you want for conductr, and then invoke the ProdServerStart.start.  Once it returns, you can call back to conductr to say that the app has started.

**Comment by huntc** [comment]
Thanks @jroper - I'll wait for the RC then to go all the way with the properties based approach in the project-doc code base.

I like the idea of providing a main class for play-conductr-bundle-lib. Given that this library has a separate lifecycle to ConductR itself I can make a release of it once the RC becomes available.

Thanks again. 'hope that you like the other changes as per our discussion.

**Comment by huntc** [comment]
@edwardcallahan Can you please release this to conductr.typesafe.com - I've already got it running on milo.

**Comment by huntc** [comment]
I also observed replication working between project-doc instances on milo. :-)

**Comment by edwardcallahan** [comment]
@huntc play-conductr-bundle-lib version 0.9.0-4158e00ea986c1b619378d5ba8bc364d34acfc0d is not published

**Comment by huntc** [comment]
Hmmm - it is there...:

http://private-repo.typesafe.com/typesafe/simple/maven-releases/com/typesafe/conductr/play-conductr-bundle-lib_2.11/0.9.0-4158e00ea986c1b619378d5ba8bc364d34acfc0d

**Comment by edwardcallahan** [comment]
Ah, it's in private-repo. That is why. Private-repo is not being tried.

**Comment by huntc** [comment]
I've now updated the resolver on master

**Comment by edwardcallahan** [comment]
Sorry, but that does not allow the build to resolve from private-repo. Same as before.

**Comment by huntc** [comment]
OK, it should really be fixed now - I've overhauled the approach to handling different versions of Play/Akka.

**Pull request merged**
