### PR TITLE
Generalised Application so that it now routes by host header

### PR DESCRIPTION
**Pull request by huntc**

### CODE REVIEW

**Comment by huntc** [comment]
@edwardcallahan Can you please review and also try it out - this now routes by HOST header and should support future projects. See what you think.

**Comment by edwardcallahan** [comment]
That works real nice for the conductr named host itself. Nice. 

In order to stage this for testing, I edited docRenderers to support the test cluster hostname. That is a concern for any staging test setup. Can we support this via config?

What I haven't been able to do is get this responding to multiple hostnames in the single app. ConductR won't put a hostname in haproxy.cfg w/out an endpoint. If we put multiple endpoints, each endpoint gets a port mapping, but only the port used in the start command is bound. How would we deploy this under multiple hostnames?

**Comment by huntc** [comment]
Can you post your config? Multiple services with just hosts should work

**Comment by edwardcallahan** [comment]
``` bash
BundleKeys.endpoints := Map(
    "webdoc" -> Endpoint("http", 0, Set(URI("http://milo.typesafe.com"))),
    "webdoc" -> Endpoint("http", 0, Set(URI("http://conductr-test.typesafe.com")))
    )
```

Duplicate name, only the last is honored

``` bash
BundleKeys.endpoints := Map(
    "webdoc" -> Endpoint("http", 0, Set(URI("http://milo.typesafe.com"))),
    "webdoctest" -> Endpoint("http", 0, Set(URI("http://conductr-test.typesafe.com")))
    )
```

Multiple ports, only the start command port is bound, resulting in an invalid mapping in haproxy.cfg. 
Specifically:

``` bash
backend httpconductrtesttypesafecom
  mode http
  server httpconductrtesttypesafecom-100023110609 10.0.0.231:10609 maxconn 1024
backend httpmilotypesafecom
  mode http
  server httpmilotypesafecom-100023110917 10.0.0.231:10917 maxconn 1024
```

Where only 10917 is bound and 10609 is not listening.

**Comment by huntc** [comment]
Where you see the Set(URI(... you should have multiple URIs...

**Comment by edwardcallahan** [comment]
Ah. Thanks,  mate.

**Comment by huntc** [comment]
> In order to stage this for testing, I edited docRenderers to support the test cluster hostname. That is a concern for any staging test setup. Can we support this via config?

Any thoughts on how you'd like the config to look?

**Comment by edwardcallahan** [comment]
An object of hostname to project key/value pairs works well for env var stuff.

**Comment by huntc** [comment]
@edwardcallahan Done.

**Comment by edwardcallahan** [comment]
Thanks for pulling that out into conf. 

``` bash
BundleKeys.endpoints := Map("webdoc" -> Endpoint("http", 0, Set(URI("http://conductr-test.typesafe.com"),URI("http://milo.typesafe.com"))))
```

Works as advertised.

**Comment by huntc** [comment]
That's great Ed! Now we have a solution that is quite adaptable for other project docs. :-)

**Pull request merged**
