### PR TITLE
WIP - DO NOT MERGE - Documentation overhaul

### PR DESCRIPTION
**Pull request by markusjura**
Changed documentation styling:
- Using now a white background
- Changed font color from navy to slate
- Changed code blocks (`code` and `pre`)
- Increased relative width of documentation text and reduced relative width of table of content
- Increased padding of `p` sections
- Reduced `row-width`from 1200 to 1000 which results in the same row margin of `62.5em` as on [typesafe.com](http://typesafe.com)
- Changed `white-dkr` styling to `white-ltr`

### CODE REVIEW

**Comment by huntc** [comment]
Thanks for this - has this been done in conjunction with @rasummer ?

**Comment by markusjura** [comment]
The idea was that I am creating a first draft and afterwards he does a review

@rasummer: Can you please do a review of the styling?

@huntc: Would be also nice to get feedback about the styling from you and the team.

The styling is IMO complete, but there are still some other topics missing which has been described in the [ConductR documentation improvements doc](https://docs.google.com/document/d/17-rKGWXnusKb3nWQBCy2_nOmVSVVlvodFYadpIps9N4/edit):
- Use code tabs (as in Play)
- Add HTML ids for each headline
- Add a clickable icon which links to the chapter (Akka has that as well)
- Add documentation item to top navigation bar
- Remove toc from landing page (separate section, not part of documentation)
- Restructuring the table of content

Would like to work on these topics today.

**Comment by rasummer** [comment]
@markusjura @huntc I'll try to take a look today, if not then Tuesday.

**Comment by markusjura** [comment]
**UPDATE**
- Top navigation menu has changed. Added the section documentation
- Footer has changed and only displays the items of the top navigation bar (instead of the documentation toc)
- Landing page doesn't contain the documentation toc anymore
- HTML ids for each headline have been added by upgrading to the latest `play-doc` version
- Anchor icon for each headline has been added to [play-doc](https://github.com/playframework/play-doc) with the PR [#17](https://github.com/playframework/play-doc/pull/17). The corresponding in `project-doc` styling has been added with the commit https://github.com/markusjura/project-doc/commit/17307ecd6b3b6a4335a8d02971c64ea94adc7e08. When `play-doc` has merged the PR we can update the version here in this project to add the feature.
- Header is not fixed anymore. This is necessary in order that the new anchor icon linking to the correct position within the page
- Added code syntax highlighting with commit 06dfc226ad795ac84c6196eec30c2aa1c742bb9b

**Comment by rasummer** [comment]
@markusjura @huntc I've taken a look at the updates and they LGTM. 

Per our discussion Markus, here's the recommendation for a CSS fix for extra long words that cause html elements such as tables to break out of their containing columns. For example, the first table on the following page is wider than the containing column: http://conductr.typesafe.com/developer/Bundle-Env.html 

``` css
.wrap {
  word-break: break-all;
}
```

The documentation creator would add the class of 'wrap' to a parent element such as the `<td>` that contains the long word. For example: `<td class="wrap">`

**Comment by huntc** [comment]
Thanks for the feedback @rasummer !

@markusjura please note that this no longer merges. Also, I'm changing the title to note that this is still a WIP. Please change the title once you're ready for it to be merged.

**Comment by huntc** [comment]
LGTM - merge at will.

Awesome work!

**Comment by markusjura** [comment]
**UPDATE**
- Added version of documentation to sidebar
- HTTP URI contains now the version of the documentation (currently 1.0.x)
- Added support to list down the toc on the documentation homepage (see [here](https://github.com/markusjura/conductr-doc/blob/restructure-content/src/main/play-doc/Home.md))
- Resources (e.g. images) are now streamed to the client (non-blocking)

**Attention**
This PR need to be merged together with the [#32](https://github.com/typesafehub/conductr-doc/pull/32) of [conductr-doc](https://github.com/typesafehub/conductr-doc).

**Testing**
This PR can be tested (without merging the PR from `project-doc`) by changing the documentation archive in [ConductRDocRendererModule.scala](https://github.com/markusjura/project-doc/blob/styling-updates/app/modules/ConductRDocRendererModule.scala) from `https://github.com/typesafehub/conductr-doc/archive/master.zip` to `https://github.com/markusjura/conductr-doc/archive/restructure-content.zip`

**Pull request merged**
